add rounded logo option to header
Solvro/mobile-catchqr pull request #13
Opened 2024-07-17 13:38 UTC by DimaGolt

Added rounded factory constructor for home header.
![ezgif-2-e964e3a3f1](https://github.com/user-attachments/assets/68ca8ba0-af2e-40d7-9fcf-a51092847344)

2024-07-18 19:09 UTC, mikolaj-jalocha reviewed
Like @simon-the-shark good job with initial sliver header code :-) In my opinion clean way here of dealing with 2 types of headers. 

I just left one note regarding final variable :-)

2024-07-18 19:09 UTC, mikolaj-jalocha commented on lib/features/greeting_screen/greeting_screen.dart
> +  bool isHomeHeader = true;
This could be final I guess

2024-07-18 19:25 UTC, simon-the-shark commented on lib/features/greeting_screen/greeting_screen.dart
> +  bool isHomeHeader = true;
not really :P

2024-07-18 19:26 UTC, simon-the-shark commented on lib/features/greeting_screen/greeting_screen.dart
> +  bool isHomeHeader = true;
he uses `setState` below and changes it

2024-07-18 19:27 UTC, mikolaj-jalocha commented on lib/features/greeting_screen/greeting_screen.dart
> +  bool isHomeHeader = true;
Sorry, didn't notice

2024-07-18 19:48 UTC, simon-the-shark reviewed
Good code. I'm sure you know this, but using `method`s and `get`ters like this is not 100% optimal, cause the calculations in there are performed few times each build instead of one.
 
But I get it's not a performance issue, we do there like a one or two simple arithmetics, so won't see a real world difference (unless you have half a thread cpu and 2kb of ram)

So if you thinks it adds to readability and it was a conscious choice of yours, then go for it. Just showing you this if haven't thought of simply just this:
```dart
@override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    final bgBottomMargin = clampDouble(expandedHeight * 0.3 - shrinkOffset, 0, double.infinity);

    return Stack(
// ...
```
instead of this
```dart
 double _bgBottomMargin(double shrinkOffset) =>
      clampDouble(expandedHeight * 0.3 - shrinkOffset, 0, double.infinity);

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Stack(
// ...
```

and you can basically do this for each of your methods or getters. When you move the calcs back to the build method and assign it to variable, then maybe you will get those few splits of milliseconds :P - cause you perform each calculation only once a build and not once a usage.

But as I said, you won't see a difference with your eye. If you think yours more readable, then you can leave it this way. Just wanted to make sure you've considered this option too. In my opinion the readability is similar. You can take inspiration or not. Take care and happy coding / reading through this lengthy comment

2024-07-23 12:09 UTC, simon-the-shark requested changes

2024-07-23 12:09 UTC, simon-the-shark commented on lib/widgets/logo_header.dart
> +    double bgBottomMargin = clampDouble(expandedHeight * 0.3 - shrinkOffset, 0, double.infinity);
All of these variables can be `final` :)

2024-07-23 16:35 UTC, simon-the-shark approved these changes

2024-07-23 17:49 UTC, merged